### PR TITLE
Feat/build as module

### PR DESCRIPTION
**Pull request by julieni**
Needed changes to allow building as module from monorepo https://github.com/ovh/manager/

### CODE REVIEW

**Comment by jleveugle** [comment]
Hello @julieni,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

**Comment by antleblanc** [comment]
Hi @julieni!

I'm currently updating both `build` and `dev` entries for this package in order to pass the corresponding environment when using rollup to perform a build.

see: https://github.com/ovh-ux/ng-ovh-sidebar-menu/commit/29a9bbaef85e730446ec1e66b0d5f43926c7af31 (#110)

Could you explain why a `dev:watch` entry is needed?
Because we already pass the `-w` (`--watch`) parameter to `rollup`.

**Comment by julieni** [comment]
Hello @antleblanc,

maybe I dit it the wrong way, when working on https://github.com/ovh/manager/pull/1833, which required some updates in  ovh-ux/ng-ovh-sidebar-menu

* forked ng-ovh-sidebar-menu repo
* put it as a git submodule in `packages/manager/modules/sidebar-menu` in my manager project
* then wanted to start developing the manager live with `yarn start dev:watch`

At this point, the build process hangs at watching changes in the `packages/manager/modules/sidebar-menu`, but does not go any further and whole manager does not build.

So I took a look at  `packages/manager/modules/server-sidebar/package.json` and updated commands on that basis.

Then manager build completed successful

**Comment by antleblanc** [comment]
To work with external packages we use `yarn link` (symlinks) command.
**Documentation**: https://yarnpkg.com/lang/en/docs/cli/link/

Assuming we want to start the Web control panel with a current patch to address
inside `@ovh-ux/ng-ovh-sidebar-menu`, here is the steps:

From the clone of [`ng-ovh-sidebar`](https://github.com/ovh-ux/ng-ovh-sidebar-menu) package:

```sh
$ yarn link
$ yarn run dev
```

From the clone of the monorepo [`manager`](https://github.com/ovh/manager):

**1. Link the package**

```sh
$ yarn link "@ovh-ux/ng-ovh-sidebar-menu"
```

**2. Disable symlinks inside the webpack configuration**

```diff
diff --git a/packages/manager/apps/web/webpack.config.js b/packages/manager/apps/web/webpack.config.js
index 8f2c0a1042f3..4a7fa0df2723 100644
--- a/packages/manager/apps/web/webpack.config.js
+++ b/packages/manager/apps/web/webpack.config.js
@@ -91,6 +91,7 @@ module.exports = (env = {}) => {
     },
     resolve: {
       mainFields: ['module', 'browser', 'main'],
+      symlinks: false,
     },
     plugins: [
       new webpack.DefinePlugin({
```

**3. Then start the application:**

```sh
$ cd packages/manager/apps/web
$ yarn run start:dev
```

We are currently fixing the webpack configuration of the Web control panel,
needed to achieve previous steps.
See: https://github.com/ovh/manager/pull/2035

I'm also working on a documentation to easily start with the monorepo and the
ecosystem of our packages. I will add this steps.

Hope that helps you!

**Comment by julieni** [comment]
Hi, I tried with yarn link, which seemed to work (pointing to the right path), but then either build hanged or did not use the updated source code, can't remember exactly.
I think I may have missed the `yarn run dev`, because the manager build process was looking for some `dist/` files and they weren't there.

You are right BTW, we really miss documentation on how to use all the packages and build process, and for sure a little bit more for me, as I am not part of OVH ;)

**Comment by julieni** [comment]
Ok, it works with `yarn link`, but only after updating webpack config to implement the resolve mainFields and symlinks properties.

**Pull request closed without merging**
