### PR TITLE
Feat/item hide

### PR DESCRIPTION
**Pull request by julieni**
needed here: https://github.com/ovh/manager/pull/1833

### CODE REVIEW

**Comment by antleblanc** [comment]
Thanks @julieni for your contribution.

We know there are some improvements to do on the sidebar that's why we are
currently working on a beta in order to increase performance.

This beta will bring a new way of accessing to your services or billing account
and also provides a search engine.

Here is the current draft: https://github.com/ovh/manager/pull/1841 (feat/telephony-list)

If you want to test it you just have to put in your localStorage this following
key:

```txt
ACCOUNT_BETA_FEATURES: true
```

We plan to deploy it in the next release.

Stay tuned!

**Comment by jleveugle** [comment]
Hello @julieni,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

**Comment by julieni** [comment]
reopen ?

**Comment by julieni** [comment]
Reopened as https://github.com/ovh-ux/ng-ovh-sidebar-menu/pull/111

**Pull request closed without merging**
